version: '3.9'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    privileged: true
    volumes:
      - '/home/ubuntu/Files:/srv:rshared'
    ports:
      - '3007:3007'
    restart: unless-stopped
